### ISSUE TITLE
how to fix this ????

### ISSUE THREAD

**Issue by B427** [alexlostorto/sparx#1]
ummm its says service worker inactive  how to fix also the background isn't working
[sparx-main (3).zip](https://github.com/alexlostorto/sparx/files/10892874/sparx-main.3.zip)

**Comment by alexlostorto** [comment]
The chrome extension should actually work without the background script (I will remove all unnecessary files with the next release) but the Sparx extension should still work even without the errors... Are you logged into Sparx and nothing changes?

**Comment by alexlostorto** [comment]
I have removed the background script, so there should be no error about a service worker.
